name: Solar-System-Project

on:
    workflow_dispatch: 
    push: 
        branches: 
            - main
            - 'feature/*'
env:
   MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
   MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
   MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}  # Added the environment variables into repositiory level variables and secrets into github.
jobs:
    unit_testing:
        name: Unit testing
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                operating_system: [ubuntu-latest, macos-latest]
                exclude:
                   - nodejs_version: 18
                     operating_system: macos-latest
        runs-on: ${{ matrix.operating_system}}
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4

            - name: Install Nodejs version - ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}

            - name: Install Dependencies
              run: npm install
            
            - name: Run Unit Testing
              run: npm test

            - name: Archive/Upload Artifcat
              uses: actions/upload-artifact@v4
              with:
                name: test-job-result
                path: test-results.xml
              