name: Solar-System-Project

on:
    workflow_dispatch: 
    push: 
        branches: 
            - main
            - 'feature/*'
jobs:
    unit_testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Repository
              uses: actions/checkout@v4

            - name: Install Nodejs version
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install
            
            - name: Run Unit Testing
              run: npm test